services:
  - type: web
    name: ac-mcp-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: ac-mcp-server
    envVars:
      - key: https://churchfuel.api-us1.com
        sync: false
      - key: 00fb3b7f8c5589934b9e13ed1a2f1a28682233592dcb8726324500d90de7cadb42f00df5
        sync: false
