services:
  - type: web
    name: ac-mcp-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: python3 -m fastmcp.server
    envVars:
      - key: ACTIVE_CAMPAIGN_API_URL
        sync: false
      - key: ACTIVE_CAMPAIGN_API_KEY
        sync: false
